<?php
require __DIR__.'/includes/db.php';require_once __DIR__.'/includes/functions.php';require_once __DIR__.'/includes/validation.php';
$id=$_GET['id']??null;if(!positive_integer($id)){http_response_code(400);die('Cierre no válido.');}
$stmt=$pdo->prepare('SELECT c.*,rs.version rule_version FROM monthly_closings c LEFT JOIN rule_sets rs ON rs.id=c.rule_set_id WHERE c.id=?');$stmt->execute([$id]);$closing=$stmt->fetch();if(!$closing){http_response_code(404);die('Cierre no encontrado.');}
$stmt=$pdo->prepare('SELECT * FROM monthly_closing_groups WHERE closing_id=? ORDER BY group_name');$stmt->execute([$id]);$groups=$stmt->fetchAll();
$stmt=$pdo->prepare('SELECT * FROM monthly_valuations WHERE closing_id=? ORDER BY group_name,animal_tag');$stmt->execute([$id]);$valuations=$stmt->fetchAll();
$stmt=$pdo->prepare('SELECT movement_type,COUNT(*) quantity,SUM(amount) amount FROM closing_movements WHERE closing_id=? GROUP BY movement_type ORDER BY movement_type');$stmt->execute([$id]);$movements=$stmt->fetchAll();
$stmt=$pdo->prepare('SELECT * FROM closing_audit WHERE closing_id=? ORDER BY id DESC');$stmt->execute([$id]);$audit=$stmt->fetchAll();
include __DIR__.'/includes/header.php';
?>
<div class="hero"><div><h1>Cierre <?=htmlspecialchars(substr($closing['month_end'],0,7))?></h1><p>Huella de reglas: <code><?=htmlspecialchars($closing['rules_hash'])?></code></p></div><span class="badge <?=$closing['status']==='REOPENED'?'warn':''?>"><?=htmlspecialchars(label_es($closing['status']))?></span></div>
<p class="button-row"><a class="btn" href="exports/closing_csv.php?id=<?=$id?>">Descargar CSV</a><a class="btn secondary" href="closing_print.php?id=<?=$id?>" target="_blank">Imprimir / PDF</a><a class="btn secondary" href="closings.php">Volver</a></p>
<section class="grid"><div class="card kpi"><div class="label">Activo inicial</div><div class="value"><?=money_crc((float)$closing['opening_asset'])?></div></div><div class="card kpi"><div class="label">Activo final</div><div class="value"><?=money_crc((float)$closing['closing_asset'])?></div></div><div class="card kpi"><div class="label">Resultado operativo</div><div class="value"><?=money_crc((float)$closing['operating_result'])?></div></div><div class="card kpi"><div class="label">Resultado ajustado</div><div class="value"><?=money_crc((float)$closing['adjusted_result'])?></div></div></section>
<div class="card full"><h3>Resultado por grupo</h3><table><tr><th>Grupo</th><th>Inicial</th><th>Final</th><th>Resultado biológico</th><th>Insumos</th><th>Mano de obra</th><th>Carga financiera</th><th>Ajustado</th><th>Conciliación</th></tr><?php foreach($groups as $g):?><tr><td><?=htmlspecialchars($g['group_name'])?></td><td><?=money_crc((float)$g['opening_asset'])?></td><td><?=money_crc((float)$g['closing_asset'])?></td><td><?=money_crc((float)$g['biological_result'])?></td><td><?=money_crc((float)$g['supplies_cost'])?></td><td><?=money_crc((float)$g['labor_cost'])?></td><td><?=money_crc((float)$g['financial_charge'])?></td><td><?=money_crc((float)$g['adjusted_result'])?></td><td><?=money_crc((float)$g['reconciliation_difference'])?></td></tr><?php endforeach;?></table></div>
<div class="card full"><h3>Movimientos incluidos</h3><table><tr><th>Tipo</th><th>Registros</th><th>Monto</th></tr><?php foreach($movements as $m):?><tr><td><?=htmlspecialchars(label_es($m['movement_type']))?></td><td><?=$m['quantity']?></td><td><?=money_crc((float)$m['amount'])?></td></tr><?php endforeach;?></table></div>
<div class="card full"><h3>Valorización individual (<?=count($valuations)?> animales)</h3><table><tr><th>Animal</th><th>Grupo</th><th>Ubicación</th><th>Último peso real</th><th>Peso valorizado</th><th>Método</th><th>Precio/kg</th><th>Valor</th></tr><?php foreach($valuations as $v):?><tr><td><?=htmlspecialchars($v['animal_tag'])?></td><td><?=htmlspecialchars($v['group_name'])?></td><td><?=htmlspecialchars($v['location_name']??'')?></td><td><?=$v['actual_weight_kg']!==null?htmlspecialchars($v['actual_weight_kg'].' kg · '.$v['actual_weight_date']):'—'?></td><td><?=htmlspecialchars($v['projected_weight_kg'])?> kg</td><td><?=htmlspecialchars(label_es($v['valuation_method']))?></td><td><?=money_crc((float)$v['price_per_kg'])?></td><td><?=money_crc((float)$v['value_crc'])?></td></tr><?php endforeach;?></table></div>
<div class="card full"><h3>Auditoría</h3><table><tr><th>Fecha</th><th>Acción</th><th>Usuario</th><th>Motivo</th></tr><?php foreach($audit as $a):?><tr><td><?=htmlspecialchars($a['created_at'])?></td><td><?=htmlspecialchars(label_es($a['action_type']))?></td><td><?=htmlspecialchars($a['action_by'])?></td><td><?=htmlspecialchars($a['reason']??'')?></td></tr><?php endforeach;?></table></div>
<?php include __DIR__.'/includes/footer.php';?>
