<?php
require __DIR__.'/includes/db.php';require_once __DIR__.'/includes/validation.php';require_once __DIR__.'/includes/functions.php';require_once __DIR__.'/includes/periods.php';require_once __DIR__.'/includes/warehouse_service.php';
$costTypes=['INSUMO','MATERIAL','VETERINARIO','ALIMENTACION','OTRO'];$errors=[];$message='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $source=($_POST['cost_source']??'DIRECT')==='WAREHOUSE'?'WAREHOUSE':'DIRECT';
  $errors=validate_fields($_POST,['group_id'=>[fn($v)=>positive_integer($v),'Seleccione un grupo válido.'],'activity_id'=>[fn($v)=>positive_integer($v),'Seleccione una actividad válida.'],'cost_date'=>[fn($v)=>date_not_future($v),'La fecha debe ser válida y no futura.'],'quantity'=>[fn($v)=>positive_number($v),'La cantidad debe ser mayor que cero.']]);
  if($source==='WAREHOUSE'&&!positive_integer($_POST['warehouse_product_id']??null))$errors['warehouse_product_id']='Seleccione un producto de bodega.';
  if($source==='DIRECT')$errors+=validate_fields($_POST,['cost_type'=>[fn($v)=>value_in($v,$costTypes),'El tipo de costo no es válido.'],'description'=>[fn($v)=>required_text($v),'La descripción es obligatoria.'],'unit'=>[fn($v)=>required_text($v,30),'La unidad es obligatoria.'],'unit_cost'=>[fn($v)=>positive_number($v),'El costo unitario debe ser mayor que cero.']]);
  if(!$errors){try{if($source==='WAREHOUSE'){warehouse_issue_to_cost($pdo,$_POST);$message='Consumo descontado de bodega y cargado al grupo.';}else{assert_period_open($pdo,$_POST['cost_date']);$amount=(float)$_POST['quantity']*(float)$_POST['unit_cost'];$s=$pdo->prepare('INSERT INTO costs(group_id,activity_id,cost_date,cost_type,description,unit,quantity,unit_cost,amount) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([$_POST['group_id'],$_POST['activity_id'],$_POST['cost_date'],$_POST['cost_type'],trim($_POST['description']),trim($_POST['unit']),$_POST['quantity'],$_POST['unit_cost'],$amount]);$message='Compra directa registrada.';} }catch(PDOException $e){$errors['general']='No fue posible registrar el costo.';}catch(Throwable $e){$errors['general']=$e->getMessage();}}
}
$groups=$pdo->query('SELECT * FROM cattle_groups WHERE active=1 ORDER BY sort_order,name')->fetchAll();$activities=$pdo->query('SELECT * FROM activities WHERE active=1 ORDER BY name')->fetchAll();$products=$pdo->query('SELECT * FROM warehouse_products WHERE active=1 ORDER BY name')->fetchAll();$rows=$pdo->query("SELECT c.*,g.name group_name,a.name activity_name,p.product_code FROM costs c JOIN cattle_groups g ON g.id=c.group_id LEFT JOIN activities a ON a.id=c.activity_id LEFT JOIN warehouse_products p ON p.id=c.warehouse_product_id ORDER BY cost_date DESC,c.id DESC LIMIT 200")->fetchAll();include __DIR__.'/includes/header.php';
?>
<div class="hero"><div><h1>Insumos y materiales</h1><p>Registre consumos desde bodega o compras directas que no requieren control de existencias.</p></div><div class="button-row"><a class="btn" href="warehouse.php">Gestionar bodega</a><a class="btn secondary" href="labor.php">Registrar mano de obra</a></div></div>
<?php if($message):?><div class="alert success" role="status"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($errors):?><div class="alert danger" role="alert"><?=htmlspecialchars(implode(' ',array_values($errors)))?></div><?php endif;?>
<form method="post" id="cost-form"><?=csrf_input()?><div class="row">
<div><label for="cost-source">Origen</label><select id="cost-source" name="cost_source"><option value="WAREHOUSE"<?=(($_POST['cost_source']??'WAREHOUSE')==='WAREHOUSE'?' selected':'')?>>Consumo de bodega</option><option value="DIRECT"<?=(($_POST['cost_source']??'')==='DIRECT'?' selected':'')?>>Compra directa</option></select></div>
<div><label>Grupo</label><select name="group_id"><?php foreach($groups as $g):?><option value="<?=$g['id']?>"><?=htmlspecialchars($g['name'])?></option><?php endforeach;?></select></div><div><label>Actividad</label><select name="activity_id"><?php foreach($activities as $a):?><option value="<?=$a['id']?>"><?=htmlspecialchars($a['name'])?></option><?php endforeach;?></select></div><div><label>Fecha</label><input type="date" name="cost_date" max="<?=date('Y-m-d')?>" value="<?=htmlspecialchars($_POST['cost_date']??date('Y-m-d'))?>" required></div>
<div class="warehouse-field wide"><label for="warehouse-product">Producto de bodega</label><select id="warehouse-product" name="warehouse_product_id"><option value="">Seleccione un producto…</option><?php foreach($products as $p):?><option value="<?=$p['id']?>" data-unit="<?=htmlspecialchars($p['unit'])?>" data-stock="<?=htmlspecialchars($p['current_stock'])?>" data-cost="<?=htmlspecialchars($p['average_unit_cost'])?>"><?=htmlspecialchars($p['product_code'].' · '.$p['name'].' · disponible '.number_format((float)$p['current_stock'],2,',','.').' '.$p['unit'])?></option><?php endforeach;?></select><small id="warehouse-availability" class="form-help"></small></div>
<div class="direct-field"><label>Tipo</label><select name="cost_type"><?php foreach($costTypes as $type):?><option value="<?=$type?>"><?=htmlspecialchars(label_es($type))?></option><?php endforeach;?></select></div><div class="direct-field wide"><label>Descripción</label><input name="description" maxlength="255" value="<?=htmlspecialchars($_POST['description']??'')?>"></div><div class="direct-field"><label>Unidad</label><input name="unit" maxlength="30" placeholder="kg, dosis, unidad…" value="<?=htmlspecialchars($_POST['unit']??'unidad')?>"></div>
<div><label>Cantidad</label><input id="cost-quantity" type="number" min="0.01" step="0.01" name="quantity" value="<?=htmlspecialchars($_POST['quantity']??'1')?>" required></div><div class="direct-field"><label>Costo unitario</label><input type="number" min="0.01" step="0.01" name="unit_cost" value="<?=htmlspecialchars($_POST['unit_cost']??'')?>"></div><div class="warehouse-field wide"><label>Notas del consumo</label><input name="notes" maxlength="500" placeholder="Responsable, lote o motivo del consumo"></div>
</div><p><button class="btn">Registrar costo</button></p></form>
<div class="table-scroll"><table><thead><tr><th>Fecha</th><th>Grupo</th><th>Actividad</th><th>Origen</th><th>Tipo</th><th>Descripción</th><th>Cantidad</th><th>Monto</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=htmlspecialchars($r['cost_date'])?></td><td><?=htmlspecialchars($r['group_name'])?></td><td><?=htmlspecialchars($r['activity_name']??'Sin clasificar')?></td><td><?=htmlspecialchars($r['product_code']?'Bodega · '.$r['product_code']:'Compra directa')?></td><td><?=htmlspecialchars(label_es($r['cost_type']))?></td><td><?=htmlspecialchars($r['description'])?></td><td><?=htmlspecialchars($r['quantity'].' '.$r['unit'])?></td><td><?=money_crc((float)$r['amount'])?></td></tr><?php endforeach;?></tbody></table></div>
<script>(function(){const source=document.getElementById('cost-source');const product=document.getElementById('warehouse-product');const quantity=document.getElementById('cost-quantity');const availability=document.getElementById('warehouse-availability');const warehouse=[...document.querySelectorAll('.warehouse-field')];const direct=[...document.querySelectorAll('.direct-field')];function updateProduct(){const option=product.selectedOptions[0];if(!option||!option.value){availability.textContent='';quantity.removeAttribute('max');return;}availability.textContent='Disponible: '+option.dataset.stock+' '+option.dataset.unit+' · costo promedio: ₡'+Number(option.dataset.cost).toLocaleString('es-CR',{minimumFractionDigits:2});quantity.max=option.dataset.stock;}function update(){const isWarehouse=source.value==='WAREHOUSE';warehouse.forEach(group=>{group.hidden=!isWarehouse;group.querySelectorAll('input,select').forEach(input=>input.disabled=!isWarehouse);});direct.forEach(group=>{group.hidden=isWarehouse;group.querySelectorAll('input,select').forEach(input=>input.disabled=isWarehouse);});product.required=isWarehouse;updateProduct();}source.addEventListener('change',update);product.addEventListener('change',updateProduct);update();})();</script>
<?php include __DIR__.'/includes/footer.php';?>
