<?php
require __DIR__.'/includes/db.php';
include __DIR__.'/includes/header.php';
?>
<div class="hero manual-hero"><div><p class="eyebrow">Guía operativa</p><h1>Manual de usuario</h1></div><span class="button-row"><button class="btn" type="button" onclick="window.print()">Imprimir o guardar como PDF</button><a class="btn secondary" href="help.php">Volver a Ayuda</a></span></div>

<nav class="manual-index" aria-label="Contenido del manual">
  <strong>Contenido</strong>
  <a href="#inicio">1. Primeros pasos</a><a href="#panel">2. Panel de control</a><a href="#animales">3. Animales</a><a href="#pesajes">4. Pesajes</a><a href="#operacion">5. Operación y costos</a><a href="#resultados">6. Resultados y cierres</a><a href="#configuracion">7. Configuración</a><a href="#permisos">8. Permisos</a><a href="#buenas-practicas">9. Buenas prácticas</a>
</nav>

<article class="manual-content">
  <section id="inicio"><h2>1. Primeros pasos</h2><p>Ingrese con el usuario asignado por el administrador. El menú muestra únicamente las funciones disponibles para su perfil. En teléfonos, utilice el botón de menú ubicado en el encabezado.</p><h3>Salir de forma segura</h3><p>Al terminar, seleccione <strong>Salir</strong>. No comparta contraseñas ni deje una sesión abierta en equipos compartidos.</p></section>

  <section id="panel"><h2>2. Panel de control</h2><p>La pantalla de Inicio resume animales activos, valor estimado, ganado listo para venta y gasto del mes. La sección de atención operativa señala cobertura de pesajes, registros vencidos, animales bajo la proyección y muertes del período.</p><p>Las cifras dependen de la versión de reglas activa. Antes de tomar una decisión financiera, confirme el modelo mostrado al final del panel.</p></section>

  <section id="animales"><h2>3. Animales</h2><h3>Registrar un nacimiento</h3><ol><li>Abra <strong>Animales</strong>.</li><li>Seleccione el grupo, la ubicación, el sexo y la fecha de nacimiento.</li><li>Seleccione <strong>Registrar animal</strong>.</li></ol><p>El sistema crea el peso y el evento inicial utilizando el peso de nacimiento de la regla vigente.</p><h3>Registrar una compra</h3><p>Seleccione <strong>Compra</strong> como origen e indique fecha, peso y valor de adquisición. Estos datos forman parte del cálculo financiero.</p><h3>Editar e historial</h3><p>La opción <strong>Editar</strong> permite corregir arete, ubicación y sexo de animales activos. Para cambiar de grupo utilice Traslados. La opción <strong>Historial</strong> presenta los movimientos del animal en español y conserva la trazabilidad.</p></section>

  <section id="pesajes"><h2>4. Pesajes</h2><h3>Registro manual</h3><p>Seleccione el animal, fecha y peso. No se admiten fechas futuras, pesos no positivos ni duplicados de la misma fuente y fecha.</p><h3>Importación CSV</h3><p>El archivo debe incluir <code>tag</code>, <code>weight_date</code> y <code>weight_kg</code>. También se aceptan <code>arete</code>, <code>fecha</code> y <code>peso_kg</code>. Genere la vista previa, corrija todas las filas rechazadas y confirme la importación.</p><h3>Evaluación</h3><p>La tabla compara peso real y esperado, calcula ganancia diaria y muestra si el animal está en meta, bajo meta o con pesaje vencido.</p></section>

  <section id="operacion"><h2>5. Operación y costos</h2><h3>Nacimientos y muertes</h3><p>Los nacimientos se generan desde Animales. En Eventos se registra una muerte con fecha, justificación y referencia de evidencia; el sistema calcula su peso y valor.</p><h3>Bodega</h3><p>Administración crea los productos indicando código, categoría, unidad y existencia mínima. Registre cada compra como una entrada; el sistema recalcula el costo promedio. Los ajustes corrigen diferencias físicas y quedan registrados en el kardex.</p><h3>Insumos y materiales</h3><p>Para consumir existencias, seleccione <strong>Consumo de bodega</strong>, grupo, actividad, producto y cantidad. El sistema valida la disponibilidad, descuenta la existencia y registra el costo al promedio vigente. Use <strong>Compra directa</strong> solamente cuando el gasto no pasa por bodega.</p><h3>Personal y mano de obra</h3><p>El administrador mantiene colaboradores, actividades y tarifas. Cada registro conserva la tarifa histórica utilizada en el cálculo.</p><h3>Traslados</h3><p>Seleccione animal, grupo destino, fecha y método de peso. El sistema genera dos asientos balanceados: salida del origen y entrada al destino.</p><h3>Ventas</h3><p>Registre peso y precio real por kilogramo. La tabla compara el ingreso real con el valor proyectado por la regla vigente.</p></section>

  <section id="resultados"><h2>6. Resultados y cierres</h2><h3>Estado de resultados</h3><p>Seleccione el mes para consultar activos, compras, nacimientos, muertes, ventas, traslados, costos, resultado biológico, operativo y ajustado.</p><h3>Reportes y exportaciones</h3><p>Abra <strong>Reportes</strong>, seleccione Animales, Pesajes, Eventos, Costos, Mano de obra, Traslados, Ventas o Cierres. Puede consultar un rango de fechas o todos los registros y descargar el resultado completo en Excel o PDF.</p><h3>Cierre mensual</h3><ol><li>Compruebe que todos los movimientos estén registrados.</li><li>Genere la vista previa.</li><li>Verifique que la conciliación sea cero.</li><li>Seleccione <strong>Cerrar período</strong>.</li></ol><p>El cierre conserva la versión de reglas y una huella de verificación. Si necesita corregirlo, reabra primero el cierre más reciente e indique el motivo.</p></section>

  <section id="configuracion"><h2>7. Configuración</h2><h3>Reglas de negocio</h3><p>Finanzas o Administración puede simular nuevos valores, guardar una versión en borrador y activarla con una fecha de vigencia. Los cierres anteriores no cambian.</p><h3>Catálogos</h3><p>Administración puede crear, renombrar, ordenar, activar y desactivar ubicaciones o grupos. El botón Eliminar aparece solamente cuando no existen referencias en ningún módulo.</p><h3>Usuarios</h3><p>Administración crea cuentas, asigna perfiles, activa o desactiva accesos y restablece contraseñas. La actividad reciente permite revisar operaciones sensibles.</p></section>

  <section id="permisos"><h2>8. Permisos por perfil</h2><div class="table-scroll"><table><thead><tr><th>Función</th><th>Administrador</th><th>Operación</th><th>Finanzas</th><th>Consulta</th></tr></thead><tbody><tr><td>Consultar panel e informes</td><td>Sí</td><td>Sí</td><td>Sí</td><td>Sí</td></tr><tr><td>Animales, pesajes y eventos</td><td>Sí</td><td>Sí</td><td>No</td><td>No</td></tr><tr><td>Movimientos y consumos de bodega</td><td>Sí</td><td>Sí</td><td>No</td><td>No</td></tr><tr><td>Crear y editar productos de bodega</td><td>Sí</td><td>No</td><td>No</td><td>No</td></tr><tr><td>Costos, personal, traslados y ventas</td><td>Sí</td><td>Sí</td><td>No</td><td>No</td></tr><tr><td>Reglas y cierres</td><td>Sí</td><td>No</td><td>Sí</td><td>No</td></tr><tr><td>Catálogos y usuarios</td><td>Sí</td><td>No</td><td>No</td><td>No</td></tr></tbody></table></div></section>

  <section id="buenas-practicas"><h2>9. Buenas prácticas</h2><ul><li>Registre movimientos el día en que ocurren.</li><li>Verifique arete, fecha y grupo antes de guardar.</li><li>No reutilice identificadores de animales.</li><li>Mantenga la cobertura mensual de pesajes indicada por la regla.</li><li>Desactive catálogos en lugar de eliminarlos cuando tengan historia.</li><li>Revise la conciliación antes de cada cierre.</li><li>Use una cuenta individual y una contraseña segura.</li></ul></section>
</article>
<?php include __DIR__.'/includes/footer.php';?>
