<?php
require __DIR__.'/includes/db.php';
require_once __DIR__.'/includes/validation.php';
require_once __DIR__.'/includes/transfer_service.php';
$errors=[];$message=isset($_GET['saved'])?'La transferencia interna se registró en ambos grupos.':'';
if($_SERVER['REQUEST_METHOD']==='POST'){
    $optionalNotes=fn($v)=>$v===''||$v===null||required_text($v,500);
    $errors=validate_fields($_POST,['animal_id'=>[fn($v)=>positive_integer($v),'Seleccione un animal.'],'to_group_id'=>[fn($v)=>positive_integer($v),'Seleccione el grupo de destino.'],'transfer_date'=>[fn($v)=>date_not_future($v),'La fecha debe ser válida y no futura.'],'weight_method'=>[fn($v)=>value_in($v,['ACTUAL','PROJECTED']),'El método de peso no es válido.'],'notes'=>[$optionalNotes,'Las notas admiten hasta 500 caracteres.']]);
    if(!$errors){try{transfer_animal($pdo,(int)$_POST['animal_id'],(int)$_POST['to_group_id'],$_POST['transfer_date'],$_POST['weight_method'],trim($_POST['notes']??''));header('Location: transfers.php?saved=1');exit;}catch(Throwable $e){$errors['general']=$e->getMessage();}}
}
$animals=$pdo->query("SELECT a.id,a.tag,a.group_id,g.name group_name FROM animals a JOIN cattle_groups g ON g.id=a.group_id WHERE a.status='ACTIVO' ORDER BY a.tag")->fetchAll();
$groups=$pdo->query('SELECT * FROM cattle_groups WHERE active=1 ORDER BY sort_order,name')->fetchAll();
$rows=$pdo->query('SELECT t.*,a.tag,fg.name from_group,tg.name to_group,rs.version rule_version,(SELECT COUNT(*) FROM transfer_ledger_entries le WHERE le.transfer_id=t.id) ledger_entries FROM transfers t JOIN animals a ON a.id=t.animal_id JOIN cattle_groups fg ON fg.id=t.from_group_id JOIN cattle_groups tg ON tg.id=t.to_group_id LEFT JOIN rule_sets rs ON rs.id=t.rule_set_id ORDER BY t.transfer_date DESC,t.id DESC LIMIT 200')->fetchAll();
include __DIR__.'/includes/header.php';
?>
<div class="hero"><div><h1>Transferencias internas</h1></div></div>
<?php if($message):?><div class="alert success"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($errors):?><div class="alert danger"><?=htmlspecialchars(implode(' ',array_values($errors)))?></div><?php endif;?>
<form method="post"><div class="row"><div><label>Animal</label><select name="animal_id" required><?php foreach($animals as $a):?><option value="<?=$a['id']?>"><?=htmlspecialchars($a['tag'].' · '.$a['group_name'])?></option><?php endforeach;?></select></div><div><label>Grupo destino</label><select name="to_group_id" required><?php foreach($groups as $g):?><option value="<?=$g['id']?>"><?=htmlspecialchars($g['name'])?></option><?php endforeach;?></select></div><div><label>Fecha</label><input type="date" name="transfer_date" max="<?=date('Y-m-d')?>" value="<?=htmlspecialchars($_POST['transfer_date']??date('Y-m-d'))?>" required></div><div><label>Método de peso</label><select name="weight_method"><option value="PROJECTED">Peso proyectado a la fecha</option><option value="ACTUAL">Pesaje real de la misma fecha</option></select></div><div class="wide"><label>Notas</label><input name="notes" maxlength="500" value="<?=htmlspecialchars($_POST['notes']??'')?>"></div></div><p><button class="btn">Registrar transferencia</button></p><p class="form-help">El precio por kilogramo proviene de la regla vigente. Para seleccionar peso real debe existir un pesaje exactamente en la fecha indicada.</p></form>
<div class="card full"><h3>Transferencias registradas</h3><table><tr><th>Fecha</th><th>Animal</th><th>Origen</th><th>Destino</th><th>Método</th><th>Peso</th><th>Precio/kg</th><th>Valor interno</th><th>Regla</th><th>Balance</th></tr><?php foreach($rows as $r):?><tr><td><?=htmlspecialchars($r['transfer_date'])?></td><td><?=htmlspecialchars($r['tag'])?></td><td><?=htmlspecialchars($r['from_group'])?></td><td><?=htmlspecialchars($r['to_group'])?></td><td><?=htmlspecialchars(label_es($r['weight_method']))?></td><td><?=number_format($r['weight_kg'],2,',','.')?> kg</td><td><?=money_crc((float)$r['price_per_kg'])?></td><td><?=money_crc((float)$r['total_value'])?></td><td><?=htmlspecialchars($r['rule_version']??'')?></td><td><span class="badge <?=$r['ledger_entries']==2?'':'danger'?>"><?=$r['ledger_entries']==2?'Balanceado':'Revisar'?></span></td></tr><?php endforeach;?></table></div>
<?php include __DIR__.'/includes/footer.php';?>
