<?php
require __DIR__.'/includes/db.php';
require_once __DIR__.'/includes/validation.php';
require_once __DIR__.'/includes/functions.php';
require_once __DIR__.'/includes/warehouse_service.php';
$costTypes=['INSUMO','MATERIAL','VETERINARIO','ALIMENTACION','OTRO'];$errors=[];$message='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $action=(string)($_POST['action']??'');
  try{
    if(in_array($action,['save_product','toggle_product','delete_product'],true))require_roles(['ADMIN']);
    if($action==='save_product'){
      $validation=validate_fields($_POST,['product_code'=>[fn($v)=>is_string($v)&&preg_match('/^[A-Za-z0-9._-]{2,40}$/',$v),'El código debe tener entre 2 y 40 caracteres válidos.'],'name'=>[fn($v)=>required_text($v,160),'El nombre es obligatorio.'],'cost_type'=>[fn($v)=>value_in($v,$costTypes),'La categoría no es válida.'],'unit'=>[fn($v)=>required_text($v,30),'La unidad es obligatoria.'],'minimum_stock'=>[fn($v)=>positive_number($v,true),'La existencia mínima no es válida.']]);
      if($validation)throw new InvalidArgumentException(implode(' ',array_values($validation)));
      $id=positive_integer($_POST['product_id']??null)?(int)$_POST['product_id']:null;$values=[strtoupper(trim($_POST['product_code'])),trim($_POST['name']),$_POST['cost_type'],trim($_POST['unit']),(float)$_POST['minimum_stock']];
      if($id){$values[]=$id;$pdo->prepare('UPDATE warehouse_products SET product_code=?,name=?,cost_type=?,unit=?,minimum_stock=? WHERE id=?')->execute($values);$message='Producto actualizado.';}else{$pdo->prepare('INSERT INTO warehouse_products(product_code,name,cost_type,unit,minimum_stock) VALUES(?,?,?,?,?)')->execute($values);$message='Producto creado. Registre una entrada para asignar existencia.';}
    }elseif($action==='toggle_product'){
      if(!positive_integer($_POST['product_id']??null))throw new InvalidArgumentException('Producto no válido.');$pdo->prepare('UPDATE warehouse_products SET active=IF(active=1,0,1) WHERE id=?')->execute([(int)$_POST['product_id']]);$message='Estado del producto actualizado.';
    }elseif($action==='delete_product'){
      if(!positive_integer($_POST['product_id']??null))throw new InvalidArgumentException('Producto no válido.');$id=(int)$_POST['product_id'];$stmt=$pdo->prepare('SELECT current_stock,(SELECT COUNT(*) FROM warehouse_movements WHERE product_id=p.id) movements,(SELECT COUNT(*) FROM costs WHERE warehouse_product_id=p.id) costs_count FROM warehouse_products p WHERE id=?');$stmt->execute([$id]);$product=$stmt->fetch();
      if(!$product)throw new RuntimeException('El producto no existe.');if(abs((float)$product['current_stock'])>.0001||(int)$product['movements']>0||(int)$product['costs_count']>0)throw new RuntimeException('No se puede eliminar porque tiene existencia o movimientos asociados. Puede desactivarlo.');$pdo->prepare('DELETE FROM warehouse_products WHERE id=?')->execute([$id]);$message='Producto eliminado permanentemente.';
    }elseif($action==='movement'){
      $validation=validate_fields($_POST,['product_id'=>[fn($v)=>positive_integer($v),'Seleccione un producto.'],'movement_date'=>[fn($v)=>date_not_future($v),'La fecha debe ser válida y no futura.'],'movement_type'=>[fn($v)=>value_in($v,['ENTRY','ADJUSTMENT_IN','ADJUSTMENT_OUT']),'El movimiento no es válido.'],'quantity'=>[fn($v)=>positive_number($v),'La cantidad debe ser mayor que cero.']]);if($validation)throw new InvalidArgumentException(implode(' ',array_values($validation)));warehouse_register_movement($pdo,$_POST);$message='Movimiento de bodega registrado.';
    }
  }catch(PDOException $e){$errors[]=$e->getCode()==='23000'?'El código del producto ya existe.':'No fue posible guardar la operación de bodega.';}catch(Throwable $e){$errors[]=$e->getMessage();}
}
$products=$pdo->query('SELECT p.*,(SELECT COUNT(*) FROM warehouse_movements m WHERE m.product_id=p.id) movement_count FROM warehouse_products p ORDER BY p.active DESC,p.name')->fetchAll();$activeProducts=array_values(array_filter($products,fn($p)=>(int)$p['active']===1));
$movements=$pdo->query('SELECT m.*,p.product_code,p.name product_name,g.name group_name,a.name activity_name FROM warehouse_movements m JOIN warehouse_products p ON p.id=m.product_id LEFT JOIN cattle_groups g ON g.id=m.group_id LEFT JOIN activities a ON a.id=m.activity_id ORDER BY m.movement_date DESC,m.id DESC LIMIT 150')->fetchAll();
$stats=$pdo->query("SELECT COUNT(*) products,COALESCE(SUM(current_stock*average_unit_cost),0) inventory_value,COALESCE(SUM(active=1 AND current_stock<=minimum_stock),0) low_stock FROM warehouse_products WHERE active=1")->fetch();include __DIR__.'/includes/header.php';
?>
<div class="hero"><div><p class="eyebrow">Inventario operativo</p><h1>Gestión de bodega</h1><p>Controle entradas, ajustes, existencias mínimas y salidas imputadas a cada grupo.</p></div><div class="button-row"><a class="btn" href="costs.php">Registrar consumo</a><a class="btn secondary" href="#kardex">Ver movimientos</a></div></div>
<?php if($message):?><div class="alert success" role="status"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($errors):?><div class="alert danger" role="alert"><?=htmlspecialchars(implode(' ',$errors))?></div><?php endif;?>
<div class="grid warehouse-kpis"><article class="card kpi"><span class="label">Productos activos</span><div class="value"><?=(int)$stats['products']?></div></article><article class="card kpi"><span class="label">Valor en bodega</span><div class="value"><?=money_crc((float)$stats['inventory_value'])?></div></article><article class="card kpi"><span class="label">Bajo existencia mínima</span><div class="value"><?=(int)$stats['low_stock']?></div></article><article class="card kpi"><span class="label">Movimientos visibles</span><div class="value"><?=count($movements)?></div><div class="sub">Últimos 150 movimientos</div></article></div>
<div class="warehouse-layout"><section class="card"><div class="card-header"><div><h3>Registrar entrada o ajuste</h3><p>Las salidas por consumo se registran desde Insumos y materiales.</p></div></div><form method="post" class="nested-form"><?=csrf_input()?><input type="hidden" name="action" value="movement"><div class="row"><div><label for="movement-product">Producto</label><select id="movement-product" name="product_id" required><option value="">Seleccione…</option><?php foreach($activeProducts as $p):?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['product_code'].' · '.$p['name'].' ('.number_format((float)$p['current_stock'],2,',','.').' '.$p['unit'].')')?></option><?php endforeach;?></select></div><div><label for="movement-type">Movimiento</label><select id="movement-type" name="movement_type"><option value="ENTRY">Entrada por compra</option><option value="ADJUSTMENT_IN">Ajuste de entrada</option><option value="ADJUSTMENT_OUT">Ajuste de salida</option></select></div><div><label for="movement-date">Fecha</label><input id="movement-date" type="date" name="movement_date" max="<?=date('Y-m-d')?>" value="<?=date('Y-m-d')?>" required></div><div><label for="movement-quantity">Cantidad</label><input id="movement-quantity" type="number" name="quantity" min="0.01" step="0.01" required></div><div class="movement-cost"><label for="movement-unit-cost">Costo unitario</label><input id="movement-unit-cost" type="number" name="unit_cost" min="0.01" step="0.01"></div><div><label for="movement-reference">Referencia</label><input id="movement-reference" name="reference" maxlength="120" placeholder="Factura, orden o documento"></div><div class="wide"><label for="movement-notes">Notas</label><input id="movement-notes" name="notes" maxlength="500"></div></div><p><button class="btn">Registrar movimiento</button></p></form></section>
<?php if(can_roles(['ADMIN'])):?><section class="card"><div class="card-header"><div><h3>Nuevo producto</h3><p>La existencia inicial se registra como una entrada.</p></div></div><form method="post" class="nested-form"><?=csrf_input()?><input type="hidden" name="action" value="save_product"><div class="row"><div><label for="new-product-code">Código</label><input id="new-product-code" name="product_code" maxlength="40" pattern="[A-Za-z0-9._-]+" required></div><div class="wide"><label for="new-product-name">Nombre</label><input id="new-product-name" name="name" maxlength="160" required></div><div><label for="new-product-type">Categoría</label><select id="new-product-type" name="cost_type"><?php foreach($costTypes as $type):?><option value="<?=$type?>"><?=htmlspecialchars(label_es($type))?></option><?php endforeach;?></select></div><div><label for="new-product-unit">Unidad</label><input id="new-product-unit" name="unit" maxlength="30" placeholder="kg, saco, dosis…" required></div><div><label for="new-product-minimum">Existencia mínima</label><input id="new-product-minimum" type="number" name="minimum_stock" min="0" step="0.01" value="0" required></div></div><p><button class="btn">Crear producto</button></p></form></section><?php endif;?></div>
<section class="card warehouse-products"><div class="card-header"><div><h3>Existencias por producto</h3><p>El costo promedio se actualiza con cada entrada.</p></div></div><div class="table-scroll"><table><thead><tr><th>Código</th><th>Producto</th><th>Categoría</th><th>Unidad</th><th>Mínimo</th><th>Disponible</th><th>Costo promedio</th><th>Valor</th><th>Estado</th><?php if(can_roles(['ADMIN'])):?><th>Acciones</th><?php endif;?></tr></thead><tbody><?php foreach($products as $p):$formId='product-'.$p['id'];?><tr class="<?=((int)$p['active']===1&&(float)$p['current_stock']<=(float)$p['minimum_stock'])?'stock-low':''?>"><td><input form="<?=$formId?>" name="product_code" value="<?=htmlspecialchars($p['product_code'])?>" maxlength="40" required></td><td><input form="<?=$formId?>" name="name" value="<?=htmlspecialchars($p['name'])?>" maxlength="160" required></td><td><select form="<?=$formId?>" name="cost_type"><?php foreach($costTypes as $type):?><option value="<?=$type?>"<?=$type===$p['cost_type']?' selected':''?>><?=htmlspecialchars(label_es($type))?></option><?php endforeach;?></select></td><td><input form="<?=$formId?>" name="unit" value="<?=htmlspecialchars($p['unit'])?>" maxlength="30" required></td><td><input form="<?=$formId?>" type="number" name="minimum_stock" min="0" step="0.01" value="<?=htmlspecialchars($p['minimum_stock'])?>" required></td><td><strong><?=number_format((float)$p['current_stock'],2,',','.')?></strong></td><td><?=money_crc((float)$p['average_unit_cost'])?></td><td><?=money_crc((float)$p['current_stock']*(float)$p['average_unit_cost'])?></td><td><span class="badge"><?=((int)$p['active']===1?'Activo':'Inactivo')?></span></td><?php if(can_roles(['ADMIN'])):?><td><form id="<?=$formId?>" method="post" class="sr-only-form"><?=csrf_input()?><input type="hidden" name="action" value="save_product"><input type="hidden" name="product_id" value="<?=$p['id']?>"></form><div class="catalog-actions"><button class="btn small" type="submit" form="<?=$formId?>">Guardar</button><form method="post" class="inline-form"><?=csrf_input()?><input type="hidden" name="action" value="toggle_product"><input type="hidden" name="product_id" value="<?=$p['id']?>"><button class="btn small secondary"><?=((int)$p['active']===1?'Desactivar':'Activar')?></button></form><?php if((int)$p['movement_count']===0&&abs((float)$p['current_stock'])<.0001):?><form method="post" class="inline-form" onsubmit="return confirm('¿Eliminar permanentemente este producto?')"><?=csrf_input()?><input type="hidden" name="action" value="delete_product"><input type="hidden" name="product_id" value="<?=$p['id']?>"><button class="btn small danger">Eliminar</button></form><?php endif;?></div></td><?php endif;?></tr><?php endforeach;?></tbody></table></div></section>
<section id="kardex" class="card warehouse-movements"><div class="card-header"><div><h3>Kardex de bodega</h3><p>Entradas, salidas y ajustes con existencia resultante.</p></div></div><div class="table-scroll"><table><thead><tr><th>Fecha</th><th>Producto</th><th>Movimiento</th><th>Cantidad</th><th>Costo unitario</th><th>Valor</th><th>Existencia</th><th>Destino / referencia</th><th>Registrado por</th></tr></thead><tbody><?php foreach($movements as $m):?><tr><td><?=htmlspecialchars($m['movement_date'])?></td><td><?=htmlspecialchars($m['product_code'].' · '.$m['product_name'])?></td><td><?=htmlspecialchars(label_es($m['movement_type']))?></td><td><?=number_format((float)$m['quantity'],2,',','.').' '.htmlspecialchars($m['unit'])?></td><td><?=money_crc((float)$m['unit_cost'])?></td><td><?=money_crc((float)$m['total_value'])?></td><td><?=number_format((float)$m['stock_after'],2,',','.').' '.htmlspecialchars($m['unit'])?></td><td><?=htmlspecialchars($m['group_name']??$m['reference']??$m['notes']??'—')?></td><td><?=htmlspecialchars($m['created_by'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<script>(function(){const type=document.getElementById('movement-type');const cost=document.querySelector('.movement-cost');const input=document.getElementById('movement-unit-cost');function update(){const incoming=type.value!=='ADJUSTMENT_OUT';cost.classList.toggle('is-disabled',!incoming);input.disabled=!incoming;input.required=incoming;}type.addEventListener('change',update);update();})();</script>
<?php include __DIR__.'/includes/footer.php';?>
