<?php
require __DIR__.'/../includes/db.php';require_once __DIR__.'/../includes/validation.php';
$id=$_GET['id']??null;if(!positive_integer($id)){http_response_code(400);exit;}
$stmt=$pdo->prepare('SELECT * FROM monthly_closings WHERE id=?');$stmt->execute([$id]);$closing=$stmt->fetch();if(!$closing){http_response_code(404);exit;}
$stmt=$pdo->prepare('SELECT * FROM monthly_closing_groups WHERE closing_id=? ORDER BY group_name');$stmt->execute([$id]);$groups=$stmt->fetchAll();
$stmt=$pdo->prepare('SELECT * FROM monthly_valuations WHERE closing_id=? ORDER BY group_name,animal_tag');$stmt->execute([$id]);$valuations=$stmt->fetchAll();
header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="cierre-'.$closing['month_end'].'.csv"');
$out=fopen('php://output','wb');fwrite($out,"\xEF\xBB\xBF");
fputcsv($out,['RESUMEN DEL CIERRE'], ';');fputcsv($out,['Mes','Estado','Activo inicial','Activo final','Resultado biológico','Resultado operativo','Carga financiera','Resultado ajustado','Hash reglas'],';');fputcsv($out,[$closing['month_end'],$closing['status'],$closing['opening_asset'],$closing['closing_asset'],$closing['biological_result'],$closing['operating_result'],$closing['financial_charge'],$closing['adjusted_result'],$closing['rules_hash']],';');
fputcsv($out,[],';');fputcsv($out,['RESULTADO POR GRUPO'],';');fputcsv($out,['Grupo','Activo inicial','Activo final','Compras','Nacimientos','Muertes','Ventas reales','Ventas proyectadas','Variación venta','Transferencias entrada','Transferencias salida','Variación valorización','Insumos','Mano de obra','Resultado biológico','Resultado operativo','Carga financiera','Resultado ajustado','Diferencia conciliación'],';');foreach($groups as $g)fputcsv($out,[$g['group_name'],$g['opening_asset'],$g['closing_asset'],$g['purchases'],$g['births'],$g['deaths'],$g['external_sales'],$g['projected_sales'],$g['sale_variance'],$g['transfer_in'],$g['transfer_out'],$g['valuation_change'],$g['supplies_cost'],$g['labor_cost'],$g['biological_result'],$g['operating_result'],$g['financial_charge'],$g['adjusted_result'],$g['reconciliation_difference']],';');
fputcsv($out,[],';');fputcsv($out,['VALORIZACIÓN POR ANIMAL'],';');fputcsv($out,['Arete','Grupo','Ubicación','Peso real','Fecha peso real','Peso valorizado','Método','Precio/kg','Valor'],';');foreach($valuations as $v)fputcsv($out,[$v['animal_tag'],$v['group_name'],$v['location_name'],$v['actual_weight_kg'],$v['actual_weight_date'],$v['projected_weight_kg'],$v['valuation_method'],$v['price_per_kg'],$v['value_crc']],';');fclose($out);
